# Generated by Django 6.0.3 on 2026-04-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_account_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
