# Generated by Django 6.0.3 on 2026-04-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='converted_currency',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
