# Generated by Django 6.0.3 on 2026-04-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_transaction_converted_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='converted_currency',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
